# Generated by Django 4.2.4 on 2023-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_remove_received_profile_remove_sent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sent',
            name='sent_to',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=150),
        ),
    ]
