# Generated by Django 4.2.4 on 2023-09-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_alter_sent_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='entity',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=100),
        ),
    ]
