# Generated by Django 4.2.4 on 2023-09-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_remove_received_priority_received_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='county',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_token',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
