# Generated by Django 4.2.4 on 2023-09-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_remove_received_profile_remove_sent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fms.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sent',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fms.profile'),
            preserve_default=False,
        ),
    ]
