# Generated by Django 4.2.4 on 2023-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0009_received_profile_sent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_clerk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deputy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_governor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_token',
            field=models.PositiveIntegerField(),
        ),
    ]
