# Generated by Django 4.2.4 on 2023-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0011_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_clerk',
            field=models.BooleanField(default=True),
        ),
    ]
