# Generated by Django 4.2.4 on 2023-09-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0012_alter_profile_is_clerk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received',
            old_name='profile',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='sent',
            old_name='profile',
            new_name='uploaded_by',
        ),
    ]
