# Generated by Django 4.2.4 on 2023-09-30 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0013_rename_profile_received_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_clerk',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_deputy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_governor',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])]),
        ),
    ]
