# Generated by Django 4.2.4 on 2023-09-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0014_remove_profile_is_admin_remove_profile_is_clerk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
