# Generated by Django 4.2.4 on 2023-09-30 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0016_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])]),
        ),
    ]
